# Generated by Django 2.2.24 on 2022-02-26 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logo_image', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logo',
            name='name',
            field=models.CharField(db_index=True, help_text='logo name.', max_length=128, verbose_name='name'),
        ),
    ]
