# Generated by Django 2.2.24 on 2022-03-03 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logo_image', '0005_auto_20220303_1837'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Logo',
        ),
    ]
