# Generated by Django 2.2.24 on 2022-03-20 11:10

import colorful.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appearance', '0004_auto_20220318_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theme',
            name='color_font_header',
            field=colorful.fields.RGBColorField(blank=True, help_text='Color font title.', verbose_name='Color font title'),
        ),
    ]
