# Generated by Django 2.2.24 on 2022-03-20 11:21

import colorful.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appearance', '0005_auto_20220320_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theme',
            name='color_font_header',
            field=colorful.fields.RGBColorField(blank=True, help_text='Color font title and all content.', verbose_name='Color font title Color font title and all content.'),
        ),
    ]
